name: Build and test

on:
  push:
    branches:
    - '**'
    - '!branch-*.*'

jobs:
  # Build: build and run the tests for specified modules.
  build:
    # Ubuntu 22.04 is the latest LTS.
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    env:
      SPARK_VERSION: ${{ matrix.spark }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      # In order to fetch changed files
      with:
        fetch-depth: 0
        repository: holdenk/spark-upgrade
        ref: main
    - name: Sync the current branch with the latest in spark-testing-base
      if: github.repository != 'holdenk/spark-upgrade'
      id: sync-branch
      run: |
        apache_spark_ref=`git rev-parse HEAD`
        git fetch https://github.com/$GITHUB_REPOSITORY.git ${GITHUB_REF##*/}
        git -c user.name='Spark Test Account' -c user.email='sparktestacc@gmail.com' merge --no-commit --progress --squash FETCH_HEAD
        git -c user.name='Spark Test Account' -c user.email='sparktestacc@gmail.com' commit -m "Merged commit"
        echo "::set-output name=SPARK_REF::$apache_spark_ref"
    # Install python deps
    - name: Install python deps
      run: pip install -r python/requirements.txt
    # Run the scala tests.
    - name: Run sbt tests
      run: cd scalafix; ./build/sbt ";clean;compile;test"
    # Run Python style checks
    - name: Run Python style
      run: flake8 --max-line-length 100 --exclude  sample_inputs .
